operations:
  url: "http://identity.ibank.financial/api/v1"
institution-name: ibank
identity:
  channel:
    clients:
      - clientId: channel-ibank-usa
        clientSecret: p1234
        tenant: ibank-usa
      - clientId: channel-ibank-india
        clientSecret: p1234
        tenant: ibank-india